
//! Autogenerated weights for `pallet_orderbook`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2025-10-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Randalls-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/solochain-template-runtime/solochain_template_runtime.compact.compressed.wasm
// --pallet
// pallet_orderbook
// --extrinsic
// *
// --template
// ./pallets/benchmarking/frame-umbrella-weight-template.hbs
// --output
// ./pallets/orderbook/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

//use frame::weights_prelude::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_orderbook`.
pub trait WeightInfo {
	fn place_order() -> Weight;
	fn cancel_order() -> Weight;
	fn on_finalize_empty() -> Weight;
	fn on_finalize_with_matches(b: u32, a: u32, ) -> Weight;
	fn on_finalize_no_matches(b: u32, a: u32, ) -> Weight;
	fn on_finalize_with_cancellations(c: u32, ) -> Weight;
	fn on_finalize_persistent_matching(p: u32, n: u32, ) -> Weight;
	fn on_finalize_complex(m: u32, n: u32, c: u32, ) -> Weight;
}

/// Weights for `pallet_orderbook` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Assets::FreeBalance` (r:1 w:1)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:1 w:1)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::NextOrderId` (r:1 w:1)
	/// Proof: `Orderbook::NextOrderId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:1 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::UserOrders` (r:1 w:1)
	/// Proof: `Orderbook::UserOrders` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Orders` (r:0 w:1)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn place_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `11515`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 11515)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Orderbook::Orders` (r:1 w:0)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	fn cancel_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `289`
		//  Estimated: `3585`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3585)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Orderbook::Orders` (r:1 w:0)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:1 w:0)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:1 w:0)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:0)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	fn on_finalize_empty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `83499`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(24_000_000, 83499)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Orderbook::Orders` (r:101 w:100)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:2 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:2 w:1)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:0)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::NextTradeId` (r:1 w:1)
	/// Proof: `Orderbook::NextTradeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:100 w:100)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::FreeBalance` (r:100 w:100)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Trades` (r:0 w:50)
	/// Proof: `Orderbook::Trades` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 50]`.
	/// The range of component `a` is `[1, 50]`.
	fn on_finalize_with_matches(b: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + a * (509 ±0) + b * (510 ±0)`
		//  Estimated: `83499 + a * (2595 ±0) + b * (2595 ±0)`
		// Minimum execution time: 378_000_000 picoseconds.
		Weight::from_parts(380_000_000, 83499)
			// Standard Error: 455_618
			.saturating_add(Weight::from_parts(14_754_607, 0).saturating_mul(b.into()))
			// Standard Error: 455_618
			.saturating_add(Weight::from_parts(13_465_412, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(64_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(61_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(b.into()))
	}
	/// Storage: `Orderbook::Orders` (r:101 w:100)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:2 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:2 w:1)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:1)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:1)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 50]`.
	/// The range of component `a` is `[1, 50]`.
	fn on_finalize_no_matches(b: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `709 + a * (134 ±0) + b * (134 ±0)`
		//  Estimated: `83499 + a * (2595 ±0) + b * (2595 ±0)`
		// Minimum execution time: 338_000_000 picoseconds.
		Weight::from_parts(340_000_000, 83499)
			// Standard Error: 106_234
			.saturating_add(Weight::from_parts(2_374_357, 0).saturating_mul(b.into()))
			// Standard Error: 106_234
			.saturating_add(Weight::from_parts(2_260_042, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(b.into()))
	}
	/// Storage: `Orderbook::Orders` (r:51 w:50)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:2 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:1 w:0)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:1)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:50 w:50)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::FreeBalance` (r:50 w:50)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 50]`.
	fn on_finalize_with_cancellations(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225 + c * (359 ±0)`
		//  Estimated: `83499 + c * (2595 ±0)`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(45_799_510, 83499)
			// Standard Error: 38_272
			.saturating_add(Weight::from_parts(20_011_078, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(c.into()))
	}
	/// Storage: `Orderbook::Orders` (r:41 w:40)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:2 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:1 w:0)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:0)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:2 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::NextTradeId` (r:1 w:1)
	/// Proof: `Orderbook::NextTradeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:40 w:40)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::FreeBalance` (r:40 w:40)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Trades` (r:0 w:20)
	/// Proof: `Orderbook::Trades` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `n` is `[1, 20]`.
	fn on_finalize_persistent_matching(p: u32, n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (534 ±0) + p * (518 ±0)`
		//  Estimated: `166008 + n * (2595 ±58) + p * (2595 ±58)`
		// Minimum execution time: 203_000_000 picoseconds.
		Weight::from_parts(205_000_000, 166008)
			// Standard Error: 428_260
			.saturating_add(Weight::from_parts(12_659_114, 0).saturating_mul(p.into()))
			// Standard Error: 428_260
			.saturating_add(Weight::from_parts(13_031_874, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(34_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(30_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(p.into()))
	}
	/// Storage: `Orderbook::Orders` (r:71 w:70)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:3 w:2)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:2 w:1)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:2)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::NextTradeId` (r:1 w:1)
	/// Proof: `Orderbook::NextTradeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:50 w:50)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::FreeBalance` (r:50 w:50)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Trades` (r:0 w:20)
	/// Proof: `Orderbook::Trades` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[1, 20]`.
	/// The range of component `n` is `[1, 20]`.
	/// The range of component `c` is `[1, 10]`.
	fn on_finalize_complex(m: u32, n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187 + c * (366 ±0) + m * (713 ±0) + n * (198 ±0)`
		//  Estimated: `83499 + c * (2595 ±0) + m * (5190 ±0) + n * (2595 ±0)`
		// Minimum execution time: 429_000_000 picoseconds.
		Weight::from_parts(64_754_480, 83499)
			// Standard Error: 102_973
			.saturating_add(Weight::from_parts(44_112_949, 0).saturating_mul(m.into()))
			// Standard Error: 102_973
			.saturating_add(Weight::from_parts(6_550_077, 0).saturating_mul(n.into()))
			// Standard Error: 210_571
			.saturating_add(Weight::from_parts(21_044_681, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(7_u64))
			.saturating_add(T::DbWeight::get().writes((7_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(c.into()))
			.saturating_add(Weight::from_parts(0, 5190).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Assets::FreeBalance` (r:1 w:1)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:1 w:1)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::NextOrderId` (r:1 w:1)
	/// Proof: `Orderbook::NextOrderId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:1 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::UserOrders` (r:1 w:1)
	/// Proof: `Orderbook::UserOrders` (`max_values`: None, `max_size`: Some(8050), added: 10525, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Orders` (r:0 w:1)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	fn place_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `11515`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 11515)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Orderbook::Orders` (r:1 w:0)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	fn cancel_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `289`
		//  Estimated: `3585`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3585)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Orderbook::Orders` (r:1 w:0)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:1 w:0)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:1 w:0)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:0)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	fn on_finalize_empty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `83499`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(24_000_000, 83499)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Orderbook::Orders` (r:101 w:100)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:2 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:2 w:1)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:0)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::NextTradeId` (r:1 w:1)
	/// Proof: `Orderbook::NextTradeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:100 w:100)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::FreeBalance` (r:100 w:100)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Trades` (r:0 w:50)
	/// Proof: `Orderbook::Trades` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 50]`.
	/// The range of component `a` is `[1, 50]`.
	fn on_finalize_with_matches(b: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + a * (509 ±0) + b * (510 ±0)`
		//  Estimated: `83499 + a * (2595 ±0) + b * (2595 ±0)`
		// Minimum execution time: 378_000_000 picoseconds.
		Weight::from_parts(380_000_000, 83499)
			// Standard Error: 455_618
			.saturating_add(Weight::from_parts(14_754_607, 0).saturating_mul(b.into()))
			// Standard Error: 455_618
			.saturating_add(Weight::from_parts(13_465_412, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(64_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(a.into())))
			.saturating_add(RocksDbWeight::get().writes(61_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(b.into()))
	}
	/// Storage: `Orderbook::Orders` (r:101 w:100)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:2 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:2 w:1)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:1)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:1)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 50]`.
	/// The range of component `a` is `[1, 50]`.
	fn on_finalize_no_matches(b: u32, a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `709 + a * (134 ±0) + b * (134 ±0)`
		//  Estimated: `83499 + a * (2595 ±0) + b * (2595 ±0)`
		// Minimum execution time: 338_000_000 picoseconds.
		Weight::from_parts(340_000_000, 83499)
			// Standard Error: 106_234
			.saturating_add(Weight::from_parts(2_374_357, 0).saturating_mul(b.into()))
			// Standard Error: 106_234
			.saturating_add(Weight::from_parts(2_260_042, 0).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(b.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(a.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(a.into()))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(b.into()))
	}
	/// Storage: `Orderbook::Orders` (r:51 w:50)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:2 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:1 w:0)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:1)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:50 w:50)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::FreeBalance` (r:50 w:50)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 50]`.
	fn on_finalize_with_cancellations(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225 + c * (359 ±0)`
		//  Estimated: `83499 + c * (2595 ±0)`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(45_799_510, 83499)
			// Standard Error: 38_272
			.saturating_add(Weight::from_parts(20_011_078, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(c.into()))
	}
	/// Storage: `Orderbook::Orders` (r:41 w:40)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:2 w:1)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:1 w:0)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:0)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:2 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::NextTradeId` (r:1 w:1)
	/// Proof: `Orderbook::NextTradeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:40 w:40)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::FreeBalance` (r:40 w:40)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Trades` (r:0 w:20)
	/// Proof: `Orderbook::Trades` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `n` is `[1, 20]`.
	fn on_finalize_persistent_matching(p: u32, n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (534 ±0) + p * (518 ±0)`
		//  Estimated: `166008 + n * (2595 ±58) + p * (2595 ±58)`
		// Minimum execution time: 203_000_000 picoseconds.
		Weight::from_parts(205_000_000, 166008)
			// Standard Error: 428_260
			.saturating_add(Weight::from_parts(12_659_114, 0).saturating_mul(p.into()))
			// Standard Error: 428_260
			.saturating_add(Weight::from_parts(13_031_874, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(34_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(p.into())))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(30_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(p.into())))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(p.into()))
	}
	/// Storage: `Orderbook::Orders` (r:71 w:70)
	/// Proof: `Orderbook::Orders` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingBids` (r:3 w:2)
	/// Proof: `Orderbook::PendingBids` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingAsks` (r:2 w:1)
	/// Proof: `Orderbook::PendingAsks` (`max_values`: None, `max_size`: Some(8034), added: 10509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Bids` (r:1 w:2)
	/// Proof: `Orderbook::Bids` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Asks` (r:1 w:0)
	/// Proof: `Orderbook::Asks` (`max_values`: None, `max_size`: Some(80034), added: 82509, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::PendingCancellations` (r:1 w:1)
	/// Proof: `Orderbook::PendingCancellations` (`max_values`: Some(1), `max_size`: Some(401), added: 896, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::NextTradeId` (r:1 w:1)
	/// Proof: `Orderbook::NextTradeId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::LockedBalance` (r:50 w:50)
	/// Proof: `Assets::LockedBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Assets::FreeBalance` (r:50 w:50)
	/// Proof: `Assets::FreeBalance` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orderbook::Trades` (r:0 w:20)
	/// Proof: `Orderbook::Trades` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[1, 20]`.
	/// The range of component `n` is `[1, 20]`.
	/// The range of component `c` is `[1, 10]`.
	fn on_finalize_complex(m: u32, n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187 + c * (366 ±0) + m * (713 ±0) + n * (198 ±0)`
		//  Estimated: `83499 + c * (2595 ±0) + m * (5190 ±0) + n * (2595 ±0)`
		// Minimum execution time: 429_000_000 picoseconds.
		Weight::from_parts(64_754_480, 83499)
			// Standard Error: 102_973
			.saturating_add(Weight::from_parts(44_112_949, 0).saturating_mul(m.into()))
			// Standard Error: 102_973
			.saturating_add(Weight::from_parts(6_550_077, 0).saturating_mul(n.into()))
			// Standard Error: 210_571
			.saturating_add(Weight::from_parts(21_044_681, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().reads((6_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
			.saturating_add(RocksDbWeight::get().writes((7_u64).saturating_mul(m.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(c.into()))
			.saturating_add(Weight::from_parts(0, 5190).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 2595).saturating_mul(n.into()))
	}
}
